Feedback Link
saving-satoshi/saving-satoshi pull request #346
Opened 2023-04-02 18:42 UTC by benalleng

Closes #343

2023-04-02 23:45 UTC, ecurrencyhodler commented
One nit is that we should probably change "get stuck?" to "need help?"

I think it translates easier to other languages. Other than that LGTM!

2023-04-04 10:24 UTC, afterburn commented on components/Navbar/HelpLink.tsx
> +export default function UserButton() {
File is called HelpLink, but function is called UserButton

2023-04-04 10:25 UTC, afterburn commented on components/Navbar/HelpLink.tsx
> +          target={'_blank'}
You don't need curly braces if all you are passing is a string

2023-04-04 10:25 UTC, afterburn commented on components/Navbar/HelpLink.tsx
> +            <span className="whitespace-nowrap">Get stuck?</span>
Missing translation

2023-04-04 10:34 UTC, afterburn commented on components/Navbar/UserButton.tsx
> +        <span>{renderIconButton()}</span>
Lets try to stay away from these types of render functions, I feel they make it difficult to grasp the overall html structure at a glance for other contributors.

I would also strongly suggest to keep the markup separate from the component's logic. In this instance I would classify `toggleModal` and `hideModal` as component logic, whereas `renderIconButton` is markup so it should come after `toggleModal` and `hideModal`. Ideally we just inline it like this though:

```jsx
<span aria-describedby="navbar-tab-user">
  {!hasMounted && <div />}
  {hasMounted && isLoggedIn && (
    <button
      id="navbar-tab-user-icon"
      onClick={() => setOpenSignInModal(true)}
      aria-label="profile"
      className="text-grey-300 relative flex h-full w-12 cursor-pointer items-center justify-center md:w-16"
    >
      <Avatar avatar={user.avatar} size={30} />
    </button>
  )}
  {hasMounted && !isLoggedIn && (
    <button
      id="navbar-tab-user-login"
      onClick={() => toggleModal(true)}
      aria-label="profile"
      className="text-grey-300 relative flex h-full w-12 cursor-pointer items-center justify-center md:w-16"
    >
      <UserIcon />
    </button>
  )}
</span>
```

2023-04-04 10:34 UTC, afterburn requested changes
Thanks @benalleng, requested a couple minor changes.

2023-04-06 08:58 UTC, ecurrencyhodler approved these changes
LGTM

2023-04-07 08:52 UTC, merged