Update About Page for v1
saving-satoshi/saving-satoshi pull request #393
Opened 2023-04-18 15:42 UTC by ecurrencyhodler

Closes #370 

We can wait on merging this until Tuesday 4/25.

## Pull Request checklist

Please review the below PR requirements:

- Build was run locally and any changes were pushed
- Ensure that the title clearly describes the changes
- Issue to be referenced in the PR description rather than in the commits or PR title
- Clean commit history

2023-04-20 15:14 UTC, ecurrencyhodler commented
Great catch Saba. Thanks! Added a link now.

2023-04-21 19:12 UTC, afterburn commented on i18n/locales/en.ts
> -      paragraph_three:
You removed paragraph_three which has this result:

![image](https://user-images.githubusercontent.com/10757768/233716095-8a764901-1ace-4590-8b3f-4d30d8521c6d.png)

You should also remove the following code from `app/[lang]/about/page.tsx` on line 52:

```tsx
<p>{t('about.project.paragraph_three')}</p>
```

2023-04-21 19:12 UTC, afterburn requested changes
Hey @ecurrencyhodler I requested a small change.

2023-04-21 19:41 UTC, ecurrencyhodler commented on i18n/locales/en.ts
> -      paragraph_three:
Good catch thanks! Changes made.

2023-04-22 08:19 UTC, afterburn approved these changes

2023-05-10 11:54 UTC, shaavan reviewed
ACK

- The copy changes look great, and update the text to match the current development state.
- I have made a few nit comments that will help improve the flow of the text.

2023-05-10 11:54 UTC, shaavan commented on i18n/locales/en.ts
> +        'Saving Satoshi is a light-hearted first point of contact for coders who are curious about bitcoin development. Saving Satoshi has a mix of technical text and code-based challenges, but the c
nit:

```suggestion
        'Saving Satoshi is a light-hearted first point of contact for coders curious about Bitcoin development. Saving Satoshi has a mix of technical text and code-based challenges, but the challenges should be doable for anyone with basic coding skills. The project is free and open source, and all the art has been generated using text-to-image tools like Midjourney.',
```

2023-05-10 11:54 UTC, shaavan commented on i18n/locales/en.ts
> +        'This free and open source software (FOSS) project is in continuous development. Our goal is to take an iterative approach to incorporate feedback as we release new chapters. There are curren
nit:
```suggestion
        'This free and open source software (FOSS) project is in steady development. We aim to take an iterative approach to incorporate feedback as we release new chapters. There are currently ten chapters mapped out. However, more may be added as the project continues to grow.',
```

2023-05-10 14:42 UTC, ecurrencyhodler commented on i18n/locales/en.ts
> +        'Saving Satoshi is a light-hearted first point of contact for coders who are curious about bitcoin development. Saving Satoshi has a mix of technical text and code-based challenges, but the c
Updated!

2023-05-10 14:43 UTC, ecurrencyhodler commented on i18n/locales/en.ts
> +        'This free and open source software (FOSS) project is in continuous development. Our goal is to take an iterative approach to incorporate feedback as we release new chapters. There are curren
Thanks for zeroing on this section. I incorporated some of your suggestions but also updated the copy over all.

2023-05-11 09:33 UTC, shaavan approved these changes
ACK! 🚀

2023-05-16 14:44 UTC, merged