Add metadata and schema
saving-satoshi/saving-satoshi pull request #394
Opened 2023-04-19 03:37 UTC by ecurrencyhodler

Closes #228

## Pull Request checklist

Please review the below PR requirements:

- Build was run locally and any changes were pushed
- Ensure that the title clearly describes the changes
- Issue to be referenced in the PR description rather than in the commits or PR title
- Clean commit history

2023-04-19 15:08 UTC, benalleng requested changes
Few small changes!

2023-04-19 15:08 UTC, benalleng commented on app/head.tsx
> +<script type="application/ld+json" class="schemantra">{
``` suggestion
<script type="application/ld+json" className="schemantra">
```

2023-04-19 15:08 UTC, benalleng commented on app/head.tsx
> +}</script>
``` suggestion
</script>
```

2023-04-19 16:25 UTC, ecurrencyhodler commented
Thanks ben! I think that worked. 💪

2023-04-19 17:33 UTC, benalleng approved these changes

2023-04-19 17:47 UTC, ecurrencyhodler commented
Hmmm the pr is creating an error when the page loads. I think I should close the pr and let someone else handle this.

https://user-images.githubusercontent.com/32662508/233157770-c5d0cd9a-9dd3-4665-8267-723b1e13ce43.mov

2023-04-20 04:32 UTC, benalleng commented
It looks like Next13 has a new metadata format, as sepcified in the docs [here](https://beta.nextjs.org/docs/upgrade-guide#step-3-migrating-nexthead) and [here](https://beta.nextjs.org/docs/api-reference/metadata). I'll take a look at how they work tomorrow

2023-04-20 05:13 UTC, closed without merging