Ensure reliabile loading of chapter progress on chapters page
saving-satoshi/saving-satoshi pull request #469
Opened 2023-05-23 14:02 UTC by benalleng

Closes #468 

We have been consistently running into account progress errors, after some searching i found some minor logic errors that have been causing some problems with saving and initializing progress

*Test in an incognito window to fake first time user
[preview](https://saving-satoshi-git-fork-benalleng-outro-ch-3b878d-savingsatoshi.vercel.app/en/chapters/chapter-1/outro-1?dev=true)

2023-05-24 17:45 UTC, benalleng commented
@ecurrencyhodler I think i found the problems with our account progress, there were some odd state changes and in combination with our local -> account -> local -> account progress was easily lost.

Before I get any real code review I would like you and I to go though and really do some deep QA on this system to try and break it in every way a user could

2023-05-24 17:48 UTC, ecurrencyhodler commented
Amazing work! 

I would love to break it. haha. Do you want to do it on prod on in this pr?

2023-05-24 17:51 UTC, benalleng commented
in the most up-to-date preview of this PR [here](https://saving-satoshi-git-fork-benalleng-outro-ch-3b878d-savingsatoshi.vercel.app/). At the moment prod had issues again once we implemented backwards compatibility

2023-05-24 18:00 UTC, ecurrencyhodler commented
Okay so there's a flicker on the top right of the screen for the lock. Not a huge deal.
https://github.com/saving-satoshi/saving-satoshi/assets/32662508/5d6afe60-a406-4e67-ae28-66c564ed6b73

In this video I stop just short of completing challenge 1 by not clicking "next". But then when I go back to the chapters page I have to do redo parts 1 and 2 again. IMO it might be a lot of work to track successful completions of individual parts inside each challenge. But did want to flag it. 
https://github.com/saving-satoshi/saving-satoshi/assets/32662508/2047af90-1bd0-4549-89f8-68aaa1c18afe

2023-05-24 20:22 UTC, benalleng commented
> Okay so there's a flicker on the top right of the screen for the lock. Not a huge deal.
Going to pick up a new PR for this as it is a little bit separate from this logic

2023-05-29 15:11 UTC, shaavan commented
@benalleng 

I was reviewing the code, and I noticed that some parts of the code are identical to the older PR that are merged now (#436, #450)

Since these PRs are already merged, we can safely remove these changes from this PR. Also, it will make the code cleaner and easier to reason with.

2023-05-29 16:09 UTC, ecurrencyhodler approved these changes
tACK! Logged in with a saved account that completed ch.2. Went to Ch.1 outro-1 and ch.2 was still unlocked. Same with outro-2.

I jumped around from ch.2->ch.1 in a variety of ways. Also ch.1-Ch.2. Didn't run into any issues.

2023-05-30 09:42 UTC, afterburn commented on providers/ProgressProvider.tsx
> +      if (progress === 'CH1INT1') {
Nitpick but could we get `CH1INT1` from `lib/progress` instead?

2023-05-30 09:43 UTC, afterburn requested changes
Thanks @benalleng, requested a small change but otherwise code looks good.

2023-05-30 13:53 UTC, afterburn commented on providers/ProgressProvider.tsx
> +      if (progress === 'CH1INT1') {
Yes that, or export a new variable, as long as we can edit from the single file `lib/progress.ts` as opposed to going through the codebase to find all occurences of `CH1INT1` if we ever change it.

2023-05-31 12:38 UTC, shaavan approved these changes
ACK 🚀

Great work, @benalleng! No more loading problems!

2023-05-31 15:42 UTC, merged