Create Profile component #444
saving-satoshi/saving-satoshi pull request #486
Opened 2023-05-31 14:28 UTC by sabakhilji

Created a profile component and tested it on the sign-up modal.

I think it needs more styling will do it after review.
Attached Below is the screenshot of the profile component rendered on the signup modal:

![Screenshot (103)](https://github.com/saving-satoshi/saving-satoshi/assets/52318459/e178ec96-9b67-44d9-af3e-a9221e35ca65)

2023-05-31 14:32 UTC, sabakhilji commented
@afterburn please review.

2023-05-31 17:14 UTC, ecurrencyhodler commented
closes #444

2023-06-01 20:47 UTC, vinayaksh42 commented on components/Modals/SignUp.tsx
> +{
@sabakhilji can you uncomment the code in SignUp.tsx so that the component is visible for testing in deployment link

2023-06-02 12:18 UTC, shaavan commented
@sabakhilji 

I looked through the code, and the structure of the code matches the requirements mentioned in the description of #444. Though it still needs styling, which can be addressed further down the line. 

However, the code might need further improvement, which Kevin will be the best person to point out.

A gentle ping to @afterburn. Could you please take a look at the code? Thanks!

2023-06-05 09:48 UTC, afterburn commented on components/utils/Profile.tsx
> +        <span className="text-xl font-bold text-white">{description}</span>
You have marked the `description` prop as optional by using `?`, you are correct it should be optional. However you are _always_ rendering a `span` for it here. Instead we should only render this `span` if `description` has been set:

```jsx
{description && <span className="text-xl font-bold text-white">{description}</span>}
```

2023-06-05 09:49 UTC, afterburn commented on components/utils/Profile.tsx
> +      <div className="w-full">{children}</div>
The same applies to `children`.

2023-06-05 09:49 UTC, afterburn requested changes
Good work @sabakhilji, left some comments.

2023-06-05 16:34 UTC, sabakhilji commented
> Good work @sabakhilji, left some comments.

Thanks!! I did the required changes.

2023-06-07 14:52 UTC, sabakhilji commented on components/Modals/SignUp.tsx
> +      <Profile name='friend' description="good friend"></Profile>
done!

2023-06-07 14:53 UTC, afterburn approved these changes

2023-06-07 14:54 UTC, merged