Ch2 - Mining: Part 2 of mining challenge more realistic
saving-satoshi/saving-satoshi pull request #493
Opened 2023-06-01 22:22 UTC by vinayaksh42

Fixes: #488 

The user will now be able to find 1 block per 15 second (the same rate used in part-1 of the challenge). The 'transactions confirmed' as well as 'bitcoin earned' is updated along with 'Blocks found'.

2023-06-01 22:24 UTC, vinayaksh42 commented
Currently there is a bug with 10x mining. I am working on it

2023-06-01 22:30 UTC, ecurrencyhodler commented
Tested it. 

If you set it to 15, the 10x appears before a block is found. I think the increment should be around 9 seconds. That's 1-2 seconds before the 10x button appears.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/c85b4dce-4e68-4a0a-91ae-aace718f4b87

2023-06-01 22:38 UTC, vinayaksh42 commented
> Tested it.
> 
> If you set it to 15, the 10x appears before a block is found. I think the increment should be around 8 seconds. That's 1-2 seconds before the 10x button appears.

I have updated the timing to 8second

2023-06-01 23:42 UTC, ecurrencyhodler commented
tACK!
https://github.com/saving-satoshi/saving-satoshi/assets/32662508/7b77bab5-ebc8-437b-8a49-20000efce45c

2023-06-02 13:04 UTC, shaavan reviewed
I noticed a bug while testing the lesson.

After the first _four_ blocks are mined without pressing the `10x` button, the hash counter gets stuck on the "correct" hash, restarting again when the _fifth_ block is mined.

https://github.com/saving-satoshi/saving-satoshi/assets/85434418/1aa0a9aa-de17-442d-9a4d-aa8661a6a103

2023-06-05 09:35 UTC, afterburn commented on ui/common/MiningStatisticsHash.tsx
> +      const time = 1 * 10 * 1000
Can just be `10 * 1000`, multipying by `1` doesn't do anything.

2023-06-05 09:35 UTC, afterburn commented on content/lessons/chapter-2/mining-1.tsx
> +      }, 1 * 8 * 1000)
Same here, `8 * 1000`.

2023-06-05 09:36 UTC, afterburn requested changes
Thanks @vinayaksh42, left some comments.

2023-06-07 09:40 UTC, afterburn approved these changes

2023-06-07 09:40 UTC, merged