Add new miningProfiles component for HashChallenge variants
saving-satoshi/saving-satoshi pull request #537
Opened 2023-06-27 17:56 UTC by benalleng

Closes #503 

creates new Scrolling Profile container and 2 new lesson templates to demonstrate the functionality

2023-06-27 22:52 UTC, ecurrencyhodler commented
Okay so I tested this on desktop and mobile for chrome/firefox and apple devices.

Scrolling is smooth on desktop and mobile. 

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/f90a2629-0546-489e-8778-5e54ce1d2b5e


But it looks like the profiles are more squarish than rectangular. Will that create an issue with profile images?
![IMG_2854](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/3f33feaa-1b74-4e00-a08b-599750160a8d)

2023-06-28 00:42 UTC, benalleng commented
the width of the profiles are just hard coded shapes at the moment, once they are the actual profiles their shapes may vary _though i did try to match their sizes to the figma_

2023-06-28 02:45 UTC, ecurrencyhodler commented
Okay then tACK

2023-07-02 12:40 UTC, vinayaksh42 reviewed
the code looks good to me, just one question regarding one of the prop

2023-07-02 12:40 UTC, vinayaksh42 commented on ui/common/ProfilesContainer.tsx
> +  className?: string
Is this prop being used somewhere within the component right now?

2023-07-02 13:33 UTC, afterburn commented on content/lessons/chapter-3/index.ts
> +import * as POL1 from './pool-1'
Let's use `Solo1` / `Pool1` to match the existing naming convention.

2023-07-02 13:35 UTC, afterburn requested changes
Thanks @benalleng, small nitpick from me and agree with @vinayaksh42 that we should probably use that className somewhere.

2023-07-10 08:24 UTC, merged