Chapter 3 solo-1
saving-satoshi/saving-satoshi pull request #566
Opened 2023-07-21 15:57 UTC by benalleng

Closes #504

2023-07-24 17:10 UTC, benalleng commented
> One thing though is that the design in figma has the text on the left for the solo challenge.

What do you mean by this? 

The start button should be glowing, it might be a browser specfic error, what browser are you using to test?

2023-07-24 17:19 UTC, ecurrencyhodler commented
I'm using google chrome.

Here's a recording to show the button isn't glowing.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/55103be9-1a78-47f3-a916-ed4518c66a5c

2023-07-24 17:51 UTC, ecurrencyhodler commented
Thanks for the fix Ben. I see that when the screen is wider, the text is on the left. Here's a video showing how it looks like as I dynamically make the window smaller.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/8bbbd3ed-736c-42f2-a477-c815b863c715

2023-07-24 19:19 UTC, afterburn commented on content/lessons/chapter-3/solo-1.tsx
> +  }, [step])
You can combine this into a single `useEffect` since they have the same dependencies.

2023-07-24 19:21 UTC, afterburn requested changes
Requested small change

2023-07-24 19:28 UTC, afterburn commented on content/lessons/chapter-3/pool-1.tsx
> +      avatar: '/assets/avatars/bitrey.png',
I think for 'You' we should use the avatar of the currently logged in user (if it exists) and fall back to 1.png or perhaps a default profile icon or something:

![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/309f4da5-1207-48aa-a392-88ecfc930fb2)

2023-07-24 21:10 UTC, afterburn commented
@benalleng I'm logged in here but it still shows 1.png while my avatar is set to 5.png:

<img width="1002" alt="Screenshot 2023-07-24 at 23 09 00" src="https://github.com/saving-satoshi/saving-satoshi/assets/10757768/1e63c072-9e61-4f44-9579-05c7786d53ed">

2023-07-25 00:17 UTC, benalleng commented
> I'm logged in here but it still shows 1.png

@afterburn I wanted to confirm if you are still getting this behavior?  The code shouldn't fallback to 1.png ever, it should either be the standar icon if not logged in or your account avatar

2023-07-25 12:45 UTC, afterburn approved these changes

2023-07-25 12:46 UTC, merged