Issue505
saving-satoshi/saving-satoshi pull request #567
Opened 2023-07-21 17:55 UTC by vinayaksh42

Fixes: #505

2023-07-22 15:35 UTC, ecurrencyhodler commented
Tested. Looks like the order of challenges is a bit wonky. It currently goes from challenge 2 (Coop-lose) to challenge 1 (solo vs bitrey lose) to challenge 2 (Coop-lose).

2023-07-22 15:36 UTC, ecurrencyhodler commented
Also this comment is not a blocker but @GBKS do we need a different profile picture for bitrey?

<img width="859" alt="Screenshot 2023-07-22 at 8 33 29 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/d748cc80-6343-47d4-bbe4-41c48708c9e1">

2023-07-22 15:39 UTC, vinayaksh42 commented
> Tested. Looks like the order of challenges is a bit wonky. It currently goes from challenge 2 (Coop-lose) to challenge 1 (solo vs bitrey lose) to challenge 2 (Coop-lose).

The order will be fixed once either my PR is merged or @benalleng's PR is merged. The Bitrey picture is also different, check [this](https://saving-satoshi-dxkcu95nz-savingsatoshi.vercel.app/en/chapters/chapter-3/coop-1?dev=true). The solo and coop challenge you see in the preview of this PR will be removed.

2023-07-22 15:44 UTC, ecurrencyhodler commented
awesome! Okay then it's a tACK for me.

2023-07-24 19:25 UTC, afterburn commented on content/lessons/chapter-3/coop-1.tsx
> +      avatar: '/assets/avatars/1.png',
We should probably try to take the avatar of the currently logged in user (if it exists) and fallback to this one.

2023-07-24 19:26 UTC, afterburn requested changes
Requested small change

2023-07-25 12:47 UTC, afterburn approved these changes

2023-07-25 12:47 UTC, merged