Remove blocks from other miners in CH3COO2
saving-satoshi/saving-satoshi pull request #586
Opened 2023-07-31 14:25 UTC by benalleng

Closes #585 

in CH3COO2 only one miner is supposed to find blocks based on the nonce overlap. I created a semi-hacky way of leaving the other miners to be visible while still giving the correct number fo blocks to the protagonists / antagonists.

2023-08-01 10:59 UTC, afterburn commented on content/lessons/chapter-3/coop-2.tsx
> +
If you are passing all the data this function needs via arguments we can move this function outside of the hook.
Also I think you can use a `.reduce` for this:
```ts
const indexOfHighestScore = players.reduce((highestIndex, current, index) => 
  current.value > players[highestIndex].value ? index : highestIndex,
0)
```

2023-08-01 11:03 UTC, afterburn commented on content/lessons/chapter-3/coop-2.tsx
> +                  : '0'}
Not sure what is happening here, but I would recommend you do something like this instead:

```tsx
{i === PROFILES.length - 1 && profile.value}
{i === highestHashpowerProtagonist && profile.value + 3}
{i !== PROFILES.length - 1 && i !== highestHashpowerProtagnist && '0'}
```

While this probably takes more compute, I think its neglible if it makes it easier to parse than nested ternary operators.

2023-08-01 11:03 UTC, afterburn requested changes
Thanks @benalleng, I requested some changes

2023-08-02 02:35 UTC, ecurrencyhodler commented
CH3COO2 from a design and usability stand points works for me.

2023-08-04 15:21 UTC, GBKS commented
Not sure if related to this PR, but there seems to be an issue with how the values are displayed. See below, where the miner on the right has a higher hash rate, but ends up with a lower amount of hashes checked.

<img width="642" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/695901/e22a52ce-db18-4623-9452-1f7f13ffe4a8">

From watching the numbers a few times, it seems like the exponent is not increased at the right time. 

[Preview link I used for testing](https://saving-satoshi-git-fork-benalleng-issue585-savingsatoshi.vercel.app/en/chapters/chapter-3/coop-2?dev=true)

I'm also curious why the numbers end up differently every time I run it? Don't we have some fixed math in place? Or are the some random factors in there?

2023-08-07 17:55 UTC, afterburn approved these changes

2023-08-07 17:56 UTC, afterburn commented
@ecurrencyhodler code looks good, feel free to merge after issue flagged by @GBKS has been resolved or if we decide to address it in a separate issue

2023-08-07 20:14 UTC, GBKS commented
This should be a separate issue as it's not directly related to the code touched here. The problem is in [line 246 of coop-2.tsx](https://github.com/saving-satoshi/saving-satoshi/blob/8664cb03702b0db7ab198c44570d82aedf2d9217/content/lessons/chapter-3/coop-2.tsx#L246). For some reason, the current nonce is multiplied with the hash power when calculating the exponent. It should be just the nonce. There is a comment next to that code around wrapping this functionality into a separate component or helper, which seems like a good idea.

2023-08-07 20:52 UTC, merged