Feature flag system
saving-satoshi/saving-satoshi pull request #595
Opened 2023-08-08 09:09 UTC by afterburn

Closes #564

2023-08-08 15:27 UTC, ecurrencyhodler commented
hmmm ran into an issue. I completed ch. 1 but am unable to start ch. 2. 

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/a7ccab68-00fb-4dd0-98ae-7de5ccb5b163

2023-08-08 15:53 UTC, benalleng requested changes
One small thing otherwise Looks good!

2023-08-08 15:53 UTC, benalleng commented on providers/FeatureProvider.tsx
> +export default function ProgressProvider({
I think this should be FeatureProvider()

2023-08-11 12:01 UTC, merged

2023-08-11 14:01 UTC, benalleng commented
@ecurrencyhodler just tested this again and going from Chapter 1 to Chapter 2

2023-08-11 15:09 UTC, ecurrencyhodler commented
Ditto. it works!