Fix og image url
saving-satoshi/saving-satoshi pull request #609
Opened 2023-08-22 10:28 UTC by afterburn

Resolves #312, changed the url to use a relative path rather than an absolute one, this should make it so that Next will resolve it for the request.

2023-08-22 14:20 UTC, benalleng requested changes
Unfortunately, upon testing there doesn't seem to be a change.

I think i figured out why it isn't working.

upon inspecting the `<head>` of this deployment I noticed the description did not match the description from `app/head.tsx` but instead was coming from `app/page.tsx`.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/d2488bb3-c683-4c69-b86a-5cb29cc5b139)

 There, there is another og:image that I think is overriding the metadata here

```
openGraph: {
    title: 'Code your way through the mysteries of Bitcoin - Saving Satoshi',
    description:
      'A fun learning resource for developers to learn about how to build on bitcoin.',
    type: 'website',
    image:
      'https://imagedelivery.net/wyrwp3c-j0gDDUWgnE7lig/6818cd1b-ea0d-49a4-ea14-d34c1bbae100/public',
    url: 'https://savingsatoshi.com/',
  },
```

if we change the preview image here we might get to see some results

2023-08-23 08:47 UTC, afterburn commented
Thanks @benalleng, you're right, `page.tsx > metadata` will always override whatever we put in `app/head.tsx`. I now used a different approach that should allow us to very easily add opengraph/twitter tags to our pages by importing `defaultMetadata`, then engineers will have the ability to override those defaults, like I have done with `title` in some of the files.

2023-08-23 08:51 UTC, afterburn commented
Noticed this doesn't actually fix #312, although it does fix a metatag problem we had, so now moving on to fixing the actual bug.

2023-08-23 09:39 UTC, afterburn commented
@benalleng @ecurrencyhodler found an issue with our middleware, should be ready for review now.

<img width="1800" alt="Screenshot 2023-08-23 at 11 39 32" src="https://github.com/saving-satoshi/saving-satoshi/assets/10757768/22962469-700c-4edc-b3d2-9fd1f19c85c2">

2023-08-23 15:42 UTC, ecurrencyhodler commented
Thanks Kevin! Tested in discord but the preview seems to be smaller than anticipated. This is what I see when I paste into discord: https://saving-satoshi-b6hjyv9m0-savingsatoshi.vercel.app/
<img width="587" alt="Screenshot 2023-08-23 at 8 35 42 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/1763a5c3-2042-445b-9142-56d1ae160739">

I saw one version where @benalleng was able to generate one in discord with a bigger image:

<img width="569" alt="Screenshot 2023-08-23 at 8 35 56 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/47c81ef4-d3dd-4eae-b5fb-342ac668a6cd">

 Do you think we could make the preview image larger like this one? No worries if not.
 
 The good news is that I checked using the linkedin url and twitter and both are able to generate a preview image:
<img width="445" alt="Screenshot 2023-08-23 at 8 41 21 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/75fdcfec-2981-4817-bd0d-b207c3ed3531">
<img width="1178" alt="Screenshot 2023-08-23 at 8 38 45 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/c6d13548-55d2-4550-93bb-60802b0971f5">

2023-08-23 15:49 UTC, benalleng approved these changes
LGTM! We can just change the twitter card type to see the larger image

2023-08-23 15:49 UTC, benalleng commented on config/metadata/twitter.ts
> +    card: 'summary',
just a quick change for @ecurrencyhodler 's suggestion

```suggestion
    card: 'summary_large_image',
```

2023-08-23 21:42 UTC, merged