chore: Improved terminal colours
saving-satoshi/saving-satoshi pull request #708
Opened 2023-10-27 10:49 UTC by daviroo

- Removed css for error/success
- Made all terminal output white with 0.75 opacity
<img width="589" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/3502409/353ea3e0-5306-4935-8cee-16f14084e148">

## Pull Request checklist

Please review the below PR requirements:

- Build was run locally and any changes were pushed
- Ensure that the title clearly describes the changes
- Issue to be referenced in the PR description rather than in the commits or PR title
- Clean commit history

2023-10-27 14:08 UTC, benalleng requested changes
While this changes the output colors to be the correct opacity looking at the issue I think they want the dim error text to be changed as well. Not sure where these styles are declared though... perhaps some shadow dom from the monaco editor

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/ba943c21-6f2a-48f8-8cdf-8a904ff7a2ee)

2023-10-27 16:04 UTC, benalleng commented
tACK, looks great!

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/8d60ccb7-ff20-458c-85a1-37a72c372f03)

@GBKS the only remaining difficult-to-read code is a file path that is Not important to the user

2023-10-27 16:04 UTC, benalleng approved these changes

2023-10-27 22:35 UTC, merged

2023-11-01 10:06 UTC, GBKS commented
Is there a reason to highlight the path separately? Could also just be same color as the file name?