Chapter 5 Derive Message 7
saving-satoshi/saving-satoshi pull request #750
Opened 2023-11-14 16:50 UTC by benalleng

Closes #714

[Preview](https://saving-satoshi-git-fork-benalleng-transact-e9e210-savingsatoshi.vercel.app/en/chapters/chapter-5/derive-message-7?dev=true)

2023-11-16 11:20 UTC, daviroo requested changes

2023-11-16 11:20 UTC, daviroo commented on content/lessons/chapter-5/derive-message-7.tsx
> +      return [false, 'Be sure you filled in both the output andsig hash flag.']
```suggestion
      return [false, 'Be sure you filled in both the output and sig hash flag.']
```

2023-11-16 11:20 UTC, daviroo commented on content/lessons/chapter-5/derive-message-7.tsx
> +      return [false, 'Be sure you filled in both the output andsig hash flag.']
```suggestion
      return [false, 'Be sure you filled in both the output and sig hash flag.']
```

2023-11-27 14:30 UTC, benalleng commented on content/lessons/chapter-5/derive-message-7.tsx
> +  // output #1 scriptPubKey (Satoshi's oen public key again, for change):
``` suggestion
  // output #1 scriptPubKey (Satoshi's open public key again, for change):
```

2023-11-28 16:54 UTC, merged