Chapter Six Challenge one intro pages
saving-satoshi/saving-satoshi pull request #787
Opened 2023-12-05 20:22 UTC by 0tuedon

This PR closes #766  

Designed both intro pages for challenge one in Chapter six

2023-12-05 20:25 UTC, 0tuedon commented
Oops guess the intro one should be this issue  #766  making this a draft to change

2023-12-05 22:26 UTC, 0tuedon commented
> Oops guess the intro one should be this issue #766 making this a draft to change

Ready for review

2023-12-07 13:43 UTC, benalleng requested changes
Looks like you swapped all the file names around

2023-12-07 13:43 UTC, benalleng commented on i18n/locales/en.ts
>        title: 'The ins and outs',
You'll need to adjust the metadata titles to match this now being under in_out_two

2023-12-07 13:43 UTC, benalleng commented on public/assets/images/chapter-6-in-out-2.jpg
Let's export the image a little differently as this one seems to include its own border

2023-12-08 19:32 UTC, 0tuedon commented on public/assets/images/chapter-6-in-out-2.jpg
seems it's still the same?

2023-12-08 19:43 UTC, benalleng requested changes
few small changes but looking good!

2023-12-08 20:08 UTC, benalleng approved these changes
LGTM!

2023-12-08 20:15 UTC, merged