Read-only editor for bitcoin script
saving-satoshi/saving-satoshi pull request #803
Opened 2023-12-18 10:09 UTC by 0tuedon

This PR closes #766 and creates a new component for a read only editor without languages tab

2023-12-21 15:19 UTC, daviroo requested changes
It doesn't appear to work on mobile view and also on desktop I can see some visual bugs (screenshot below & highlighted in red)

![image](https://github.com/saving-satoshi/saving-satoshi/assets/3502409/24290ed8-1d22-420c-a9fa-3381c7476b71)

2023-12-22 17:46 UTC, 0tuedon commented
> It doesn't appear to work on mobile view and also on desktop I can see some visual bugs (screenshot below & highlighted in red)
> 
> ![image](https://private-user-images.githubusercontent.com/3502409/292245101-24290ed8-1d22-420c-a9fa-3381c7476b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjc0NTUsIm5iZiI6MTcwMzI2NzE1NSwicGF0aCI6Ii8zNTAyNDA5LzI5MjI0NTEwMS0yNDI5MGVkOC0xZDIyLTQyMGMtYTlmYS0zMzgxYzc0NzZiNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTc0NTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGFmNDgzM2E3OWUwYjQyYzJjNzQ3Y2ZiY2NiYjRkNmFhMjEyM2EyNTc2M2Y1ZDVkODhmNGY0Y2IyMjI4OGNjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jkpEvU-2_3yVNgHgMc22dKM0XmF1wJpWkPnN4v-rxcY)

Alright checking this out

2024-01-03 14:32 UTC, benalleng requested changes
I don't think we want to render it as a `<Lesson>` since this breaks it on mobile, lets just try to render it as a flex-wrap row so that on mobile it drops below? Or if we do want tabs we need to get rid of execute on this page

2024-01-03 17:04 UTC, 0tuedon commented
> I don't think we want to render it as a `<Lesson>` since this breaks it on mobile, lets just try to render it as a flex-wrap row so that on mobile it drops below? Or if we do want tabs we need to get rid of execute on this page

Yh I did figure that out, i'd prefer removing the execute on the page?

2024-01-05 18:07 UTC, benalleng commented on ui/lesson/ScriptingChallenge/PlainEditor.tsx
> +          height={`calc(var(--dynamic-height) - ${totalHeight}px)`}
I think we should try to change the height to look a little better, still need to brainstorm how to get this just right as I tried just using `100%` but I'm not totally happy with it

2024-01-08 15:21 UTC, benalleng requested changes
Last tiny change to add padding above the code

2024-01-08 15:21 UTC, benalleng commented on ui/lesson/ScriptingChallenge/PlainEditor.tsx
> +          'relative grow bg-[#00000026] font-mono text-sm text-white',
```suggestion
          'relative grow bg-[#00000026] pt-4 font-mono text-sm text-white',
```

2024-01-09 15:16 UTC, benalleng approved these changes

2024-01-09 15:58 UTC, daviroo approved these changes

2024-01-09 16:11 UTC, merged