Use global libraries instead of hidden code
saving-satoshi/saving-satoshi pull request #805
Opened 2023-12-30 16:35 UTC by daviroo

## Pull Request checklist

Please review the below PR requirements:

- Build was run locally and any changes were pushed
- Ensure that the title clearly describes the changes
- Issue to be referenced in the PR description rather than in the commits or PR title
- Clean commit history

2023-12-31 00:35 UTC, 0tuedon commented
Hey @daviroo do you have permission to add me to the backend repo not sure i have access

2023-12-31 00:36 UTC, 0tuedon commented
Hey @daviroo do you have permission to add me to the backend repo not sure i have access

2024-01-01 18:43 UTC, benalleng requested changes
Other than removing the uneccessary hidden range it's looking good!

2024-01-01 18:43 UTC, benalleng commented on content/lessons/chapter-4/address-3.tsx
> +    hiddenRange: [1, 0, 1, 0],
I think you can simply remove the hidden range if you don't want it anymore

2024-01-02 16:04 UTC, daviroo commented
> Hey @daviroo do you have permission to add me to the backend repo not sure i have access

You should be good now

2024-01-03 15:48 UTC, benalleng approved these changes

2024-01-03 15:48 UTC, merged