[WIP] Navigation Granularity
saving-satoshi/saving-satoshi pull request #880
Opened 2024-03-05 22:03 UTC by benalleng

Closes #872 

TODO
- similar navigation in Navbar and mobile Navbar
- adjust titles so that it actually makes sense for the user

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/d494b061-33d5-45ae-9e6f-87b01992825a)

2024-03-08 07:43 UTC, GBKS commented
I think we need to iterate on this a little bit more. Some things to consider:

- The most obvious part is about coming up with unique titles for each page and section, so the are distinguishable and readers understand what each one is
- The numbering is now inconsistent with the smaller number-based index at the top-right of the screen on desktop. Maybe we reserve numbers for the larger blocks and pages don't have them?
- Text pages and problem pages look the same. Text pages can't really be completed (unless you count reading as completion). Should we visually differentiate text and challenge pages? Maybe text pages don't get a check on completion?

I'd like to take a stab at this from a design perspective, just need to find a little bit of time for it.

2024-03-18 22:15 UTC, benalleng commented
@GBKS I have made an update for the chapter 1 keys I added the titles as such

- As a note I made all the challenge pages have an imperative clause as their title 

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/d661c182-7d1a-43fa-8290-51172bd1a474)

2024-04-12 08:59 UTC, GBKS commented
Sorry for taking a million years, but I finally looked at this and gathered my thoughts and put together some design tweaks. Here's a [video overview](https://youtu.be/wHi0t3i1ST8), please let me know what you think.

2024-04-15 06:59 UTC, GBKS commented
I like this update, how about you?

Here's a comparison of the current implementation and the design.

<img width="760" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/695901/77ac7f29-7292-4a9b-af2b-c354fadae7c4">

The font sizes and spacing is a little tighter in the design (and icons also slightly smaller). I intentionally did it that way so we don't run into potential issues where the nav doesn't fit vertically on shorter screens and we end up needing to scroll (which does not play well with the hover activation and our other goal of keeping the UI at 100 window height). The best test is probably to find the chapter with the most pages and see if that still works. But would be nice to tighten things up if you get a chance.

2024-04-15 17:07 UTC, benalleng commented
Unfortunately chapter 5 is simply too long, I think I agree that click to open is better so I added that but I am not sure how tall I should make the maximum height tooltip? right now it is `calc(100vh - 70px(navbar) - 56px(successbar))` but this feels too big.

you can look here
https://saving-satoshi-git-fork-benalleng-navigati-184c07-savingsatoshi.vercel.app/en/chapters/chapter-5/derive-message-4?dev=true

2024-04-16 10:31 UTC, GBKS commented
I think a max-height of 600px or so is fine, so it doesn't become unwieldy. But, MacOS has very subtle scrollbars that are not very intrusive, so it might look ugly elsewhere. Alternative is of course to keep the individual sections (`1|2|3|4`) at the top and have a separate menu for each one.

Should still be possible to make it close when you click elsewhere.

2024-04-19 15:21 UTC, benalleng commented
After some additional feedback I decided to return to the numbered tabs, its a lot easier to find your place and not as busy with all lessons visible. Also I think easier to find a good stopping place

2024-04-19 18:00 UTC, 0tuedon commented
Ready for review @benalleng ?

2024-04-19 18:10 UTC, benalleng commented
@0tuedon Yes! just finished the translations!

2024-04-20 10:41 UTC, GBKS commented
I think this works better, we avoid this whole scrolling issue.

The spacing is still a bit off compared to the design, would it be possible to tweak that? Here's a screenshot overlaid on the design (implementation spacing is much tighter, and text is centered instead of left-aligned).

<img width="515" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/695901/f11e4fb1-ce37-4a27-afb0-a3ee708c3929">

2024-04-22 16:46 UTC, 0tuedon commented
Hey @benalleng, minor addition. Could you add a cursor-disabled to this
<img width="263" alt="Screenshot 2024-04-22 at 17 45 19" src="https://github.com/saving-satoshi/saving-satoshi/assets/90271995/8b64f834-bf77-4350-98cf-e492f0ca729c">

2024-04-22 19:27 UTC, 0tuedon requested changes
Looks good!, Left some comments

2024-04-22 19:27 UTC, 0tuedon commented on content/lessons/chapter-6/put-it-together-3.tsx
>    image: '/assets/images/chapter-4-intro-1.jpg',
<del>image: '/assets/images/chapter-4-intro-1.jpg',</del>

2024-04-22 19:27 UTC, 0tuedon commented on ui/chapter/Chapter.tsx
>        progress.at(2) !== '1' &&
We don't need this anymore?

2024-04-22 20:37 UTC, 0tuedon approved these changes
LGTM!

2024-04-22 21:20 UTC, merged